(function(g){var window=this;'use strict';var N2=function(a){a.publish("cardstatechange",a.Kl()&&a.Wp()?1:0)},O2=function(a,b){var c=g.Sa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},$eb=function(a){var b=g.Km(a);
a=g.Nm(a);return new g.ym(b.x,b.y,a.width,a.height)},afb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Os(a,b,function(){g.Ps(e);c.apply(a,arguments)},d)},R2=function(a){a=g.Wa(a);
delete P2[a];g.Pg(P2)&&Q2&&Q2.stop()},cfb=function(){Q2||(Q2=new g.rp(function(){bfb()},20));
var a=Q2;a.isActive()||a.start()},bfb=function(){var a=g.Za();
g.Fg(P2,function(b){dfb(b,a)});
g.Pg(P2)||cfb()},S2=function(a,b,c,d){g.Ep.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.T=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},dfb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;efb(a,a.progress);a.progress==1?(a.j=0,R2(a),a.onFinish(),a.Gs()):a.isPlaying()&&a.ON()},efb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.T[c]-a.B[c])*b+a.B[c]},ffb=function(a,b){g.Zh.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},T2=function(a,b,c,d,e){S2.call(this,b,c,d,e);
this.element=a},gfb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
T2.call(this,a,b,c,d,e)},hfb=function(a){return Math.pow(a,3)},ifb=function(a){return 3*a*a-2*a*a*a},jfb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},U2=function(a){return a.baseUrl||null},V2=function(a,b){return g.xn(g.Ml(a,b),function(c){return!!c})},kfb=function(a,b,c){function d(ma){var X=ma.hovercardButton;
if(!X)return null;X=X.subscribeButtonRenderer;if(!X)return null;var Q=f(X.unsubscribedButtonText),Y=f(X.subscribedButtonText);if(X.subscribed){var v=f(X.subscriberCountWithUnsubscribeText);var U=f(X.subscriberCountText)}else v=f(X.subscriberCountText),U=f(X.subscriberCountWithSubscribeText);var $a=null;if(ma.signinEndpoint){$a=O2(ma,"signinEndpoint","webNavigationEndpointData","url");if(!$a){var vb,nb;$a=(nb=g.R((vb=X.signInEndpoint)==null?void 0:vb.commandMetadata,g.G1))==null?void 0:nb.url}if(!$a)return null}return Q&&
(Y||$a)?{subscribed:X.subscribed,subscribeText:Q,subscribeCount:v,unsubscribeText:Y,unsubscribeCount:U,enabled:X.enabled,signinUrl:$a,classic:ma.useClassicSubscribeButton}:null}
function e(ma){if(ma){var X=[],Q=ma.videoId;Q&&X.push("v="+Q);(Q=ma.playlistId)&&X.push("list="+Q);(ma=ma.startTimeSeconds)&&X.push("t="+ma);return"/watch?"+X.join("&")}}
function f(ma){if(!ma)return null;var X=ma.simpleText;return X?X:ma.runs?g.Ml(ma.runs,function(Q){return Q.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,E=null,H=null,L=null,N=null;if(h==="VIDEO")g.R(l,g.hy)?m=g.R(l,g.hy).url:(N=g.R(l,g.hR),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.R(l,g.hy)?m=g.R(l,g.hy).url:(N=g.R(l,g.hR),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=O2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((E=O2(l,"urlEndpoint","url"))&&(m=E),n=!0,q="new",E=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=O2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=O2(b,"title","accessibility","accessibilityData","label");var S=b.endpoint?b.endpoint.clickTrackingParams:
null,W="";if(b.metadata){var ba=f(b.metadata);ba&&(W=ba)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),tY:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,lG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,R$:n,sessionData:S?{itct:S}:null,yfa:q,BE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:V2(b.impressionUrls||[],U2),E$:V2(b.hovercardShowUrls||[],U2),clickUrls:V2(l.loggingUrls||[],U2),visualElement:g.Sw(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},lfb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:V2(a.impressionUrls||[],U2),elements:V2(a.elements||[],function(d,e){return kfb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Sw(a.trackingParams));return c},mfb=function(a){g.cY.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.T=[];this.X=!0;this.K=0;a=a.U();this.V=g.KP(a)||g.MP(a);this.events=new g.aG(this);g.P(this,this.events);this.events.S(this.player,g.AE("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.BE("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.lc);this.events.S(window,"focus",this.wda);this.load();var b=g.nh("STYLE");(g.eh("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.sh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},nfb=function(a){return a.player.getVideoData().Lf?"current":a.V?"new":"current"},W2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},ofb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=lfb(f,nfb(a))));X2(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Mw;d&&(c.postParams={ad_tracking:d});if(b=g.zMa(b))if(b=g.Sf(b),b=g.Of(b))a.C=g.Rr(b,c)},X2=function(a,b,c){c=c===void 0?!0:c;
a.player.Ze("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.T.length>0&&(a.T.forEach(function(l){l.dispose()}),a.T.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&pfb(a);c=[];d=new g.yE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.T({I:"div",N:"ytp-ce-shadow"}),g.nS(a.player,a.B.element,4),a.D=new g.Ay(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=qfb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.nS(a.player,f.element,4);var h=new g.yE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);rfb(a,f,e)}else g.dx(new g.lt("buildEndscreenElement null",
e))}a.player.df(c);a.lc()}},pfb=function(a){var b=g.Uw(),c=g.Vw();
c&&b&&a.endscreen.visualElement&&g.qr(g.px)(void 0,c,b,a.endscreen.visualElement)},qfb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.BE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",Y:Y2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",Y:{href:Z2(a,b.targetUrl),tabindex:"-1"},W:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Ip(b.title||"")},xa:b.title},{I:"div",N:b.lG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.BE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",Y:Y2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",Y:{href:Z2(a,b.targetUrl),tabindex:"-1"},W:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Ip(b.title||"")},xa:b.title},{I:"div",N:"ytp-ce-playlist-count",
W:[{I:"div",N:"ytp-ce-playlist-icon"},{I:"div",N:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.BE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ip(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",N:"ytp-ce-subscribe-container",W:[{I:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",N:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:Y2(b)}]};c=new g.T(c);var d=g.gh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.zp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.HY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.T.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.BE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",
N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"div",N:"ytp-ce-website-title",Y:{dir:g.Ip(b.title||"")},xa:b.title},{I:"div",N:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:Y2(b)},{I:"div",N:"ytp-ce-expanding-icon",Y:sfb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",N:"ytp-ce-merchandise-price-container",
W:[{I:"div",N:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.W.push({I:"div",N:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.BE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"div",N:"ytp-ce-merchandise-title",Y:{dir:g.Ip(b.title||"")},xa:b.title},c,{I:"div",N:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:Y2(b)},{I:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{I:"div",N:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.zp(c.element,"ytp-ce-placeholder");return c},Y2=function(a){if(a.tY)var b=a.tY.thumbnails;
return sfb(b?b[b.length-1].url:null)},sfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},rfb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.X&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.zp(b.element,"ytp-ce-force-expand"),$2(a,c.id,!0)):(g.Bp(b.element,"ytp-ce-force-expand"),g.Bp(b.element,"ytp-ce-element-hover"),$2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){tfb(a,b,c)});
b.listen("mouseleave",function(){ufb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.zp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){vfb(a,c,m)});
b.listen("keypress",function(m){vfb(a,c,m)});
b.listen("focus",function(){tfb(a,b,c)});
b.listen("blur",function(){ufb(a,b,c)});
b.listen("touchstart",function(){tfb(a,b,c)});
var l=g.hh("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m.stopPropagation();g.Bp(b.element,"ytp-ce-element-hover");g.Bp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.X=m.keyCode===9&&!m.shiftKey});
d(g.hh("ytp-sb-subscribe",b.element));d(g.hh("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},vfb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.yp(d,"ytp-ce-element");){g.yp(d,"subscribe-label")&&wfb(a,b);
if(g.yp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.yp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])ufb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.yfa==="new")wfb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Sf(Z2(a,b.targetUrl)),c=g.Of(c),g.oz(c,void 0,b.sessionData);else{var e=g.ZP(a.player.U())||a.player.getVideoData().Lf,f=function(){var h=Z2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.wr(h);e&&n&&(n.v||n.list)?a.player.Ip(n.v,l,n.list,!1,void 0,m||void 0):g.nz(h,l)};
wfb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Z2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.gQ(a)+b}else return"";return b},tfb=function(a,b,c){g.yp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.zp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.rp(function(){g.zp(b.element,"ytp-ce-element-hover")},200)).start():g.zp(b.element,"ytp-ce-element-hover"),a3(a,c.E$),$2(a,c.id,!0))},ufb=function(a,b,c){g.Bp(b.element,"ytp-ce-element-hover");
g.Bp(b.element,"ytp-ce-force-expand");$2(a,c.id,!1)},$2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Dp(a.j[e].element,"ytp-ce-element-shadow-show",c)},a3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||W2(a))c&&c();else{b=xfb(a,b);var e=0,f=!1,h=new g.rp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.mv(b[a],d)}},wfb=function(a,b,c){a3(a,b.clickUrls,c);
(a=g.Vw())&&b.R$&&g.Ax(a,b.visualElement)},xfb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(yfb(b[d],c));return a},yfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},zfb=function(a){return typeof a==="string"?a:""},b3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Afb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},c3=function(a){return a.value?a.value:null},d3=function(a){if(!a)return null;
var b=g.Sf(zfb(a.value));b=g.Of(b);if(!b)return null;var c=b3(a.target,Bfb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Afb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Cfb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Ffb=function(a){if(!a)return null;
var b=b3(a.type,Dfb),c=b3(a.trigger,Efb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=d3(a?a:null);return b?new Cfb(b,c,a):null},Gfb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Hfb=function(a,b){return g.Tb(a.action,b)},Ifb=function(a,b){this.context=a;
this.j=b},Jfb=function(a){return a.customMessage?e3("div","iv-card-message",a.customMessage):""},f3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",N:"iv-card-image",Y:{style:a},W:c}},Kfb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(e3("li","",c.value));return{I:"ul",N:"iv-card-meta-info",W:b}},e3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Ip(c);return{I:a,Y:b,xa:c}},Lfb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.OE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.OE+");");c.dir=g.Ip(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",N:"iv-card-link-icon"}));return{I:"div",Ka:b,Y:c,W:d}},g3=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.yj.click,5)}},Mfb=function(a,b){this.merchant=a;
this.price=b},Nfb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Ofb=function(a,b){return b?b:Nfb(a)?"current":"new"},h3=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Ta=new Map;this.Xa=new Map;this.context.J.addEventListener(g.AE("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.BE("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},i3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.PN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.qb=!1});
a.context.j.listen(b,"touchmove",function(){a.qb=!0})},Pfb=function(a){var b;
return((b=g.R(a,g.hy))==null?0:b.url)?g.R(a,g.hy).url:(a=g.R(a,g.hR))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},j3=function(a,b,c){return{SZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
m3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
rN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Qfb=function(a,b,c){h3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Ja=this.Hb=this.C=this.isInitialized=!1;this.cards=[];this.sb=this.V=this.La=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.T=this.If=this.Ga=null;this.K=0;this.Ca=new g.rp(function(){},c.Z.qk?4E3:3E3);
g.P(this,this.Ca);this.gb=new g.rp(function(){});
g.P(this,this.gb);this.Aa=new Ifb(c,function(e,f,h,l,m,n){i3(d,e,f,h,l,m,n)});
this.X=new g.T({I:"div",N:"iv-drawer",Y:{id:"iv-drawer"},W:[{I:"div",N:"iv-drawer-header",Y:{"aria-role":"heading"},W:[{I:"span",N:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",N:"iv-drawer-content"}]});g.P(this,this.X);this.D=this.X.element;this.Za=new g.Ay(this.X,330);g.P(this,this.Za);this.Jb=g.hh("iv-drawer-header-text",this.D);this.B=g.hh("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Hb&&k3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Hb=d.C)&&l3(d)});
this.Oa=new g.aG(this);g.P(this,this.Oa);this.J.addEventListener("videodatachange",this.Bu.bind(this))},Rfb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){k3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){l3(a)});
var c=b.headerText;g.uh(a.Jb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.Sw(b.trackingParams);a.T=g.Sw(b.closeTrackingParams);a.If=g.Sw(b.iconTrackingParams)},Sfb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.bb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Ox(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,yj:{},Zp:null,jk:e.trackingParams?g.Sw(e.trackingParams):null,If:f&&f.trackingParams?g.Sw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
OE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};m3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Ox(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:n3(a,c,b,f),sponsored:!1,yj:j3(f,e,f.command),Zp:f.trackingParams?g.Sw(f.trackingParams):null,jk:e.trackingParams?g.Sw(e.trackingParams):null,If:l&&l.trackingParams?g.Sw(l.trackingParams):null,imageUrl:o3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Ox(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,OE:null,title:f.title?g.Ox(f.title):"",customMessage:f.callToAction?g.Ox(f.callToAction):"",url:g.R(f.command,g.hy).url?d3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.hy).url}):null,onClickCommand:null};m3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,yj:j3(e,f,e.endpoint),Zp:e.trackingParams?g.Sw(e.trackingParams):null,jk:f.trackingParams?g.Sw(f.trackingParams):null,If:l&&l.trackingParams?g.Sw(l.trackingParams):null,channelId:g.R(e.endpoint,g.wR).browseId,customMessage:e.customText?g.Ox(e.customText):null,profileImageUrl:o3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Ox(e.channelName):"",metaInfo:[e.subscriberCountText?g.Ox(e.subscriberCountText):""],url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.wR).canonicalBaseUrl?g.R(e.endpoint,g.wR).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.wR).browseId}),onClickCommand:null};m3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,yj:j3(e,f,e.action),Zp:e.trackingParams?g.Sw(e.trackingParams):null,jk:f.trackingParams?g.Sw(f.trackingParams):null,If:l&&l.trackingParams?g.Sw(l.trackingParams):null,rI:o3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Ox(e.customMessage):null,playlistVideoCount:g.Ox(e.playlistVideoCount),title:e.playlistTitle?g.Ox(e.playlistTitle):"",metaInfo:[e.channelName?g.Ox(e.channelName):
"",e.videoCountText?g.Ox(e.videoCountText):""],url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Pfb(e.action)}),onClickCommand:null};m3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,yj:j3(e,f,e.action),Zp:e.trackingParams?g.Sw(e.trackingParams):null,jk:f.trackingParams?g.Sw(f.trackingParams):null,If:l&&l.trackingParams?g.Sw(l.trackingParams):null,rI:o3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Ox(e.lengthString):null,customMessage:e.customMessage?g.Ox(e.customMessage):null,title:e.videoTitle?g.Ox(e.videoTitle):"",metaInfo:[e.channelName?g.Ox(e.channelName):
"",e.viewCountText?g.Ox(e.viewCountText):""],isLiveNow:!!e.badge,url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Pfb(e.action)}),onClickCommand:null};m3(a,b)}}}}}a.K++},o3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},n3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Ufb=function(a,b){if(b=Tfb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Df.id),g.sh(b.cP),g.Xb(a.cards,b),a.xJ(),p3(a)},k3=function(a,b,c){if(!a.C){a.Za.show();
a.Ua=new g.rp(function(){g.zp(a.context.J.getRootNode(),g.M_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Oa.S(a.B,"mousewheel",function(h){a.Ca.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Vw();d&&a.Ga&&a.T&&g.yx(d,[a.Ga,a.T]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.T_||(f.T_=!0,Vfb(a.context.logger,f.Df.yj.SZ,b)),d&&g.yx(d,[f.Df.Zp]);N2(a.J);c&&(a.G=new g.rp(function(){a.La=a.V;a.sb.focus()},330),a.G.start())}},l3=function(a){a.C&&(a.Za.hide(),g.Vs(a.Oa),g.Bp(a.context.J.getRootNode(),g.M_.IV_DRAWER_OPEN),a.C=!1,N2(a.J),a.G&&a.G.stop(),a.G=new g.rp(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Wfb=function(a){g.Ap(a.Ib(),
[g.M_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.nS(a.J,a.D,5);a.jJ();a.V=g.hh("ytp-cards-button",a.J.getRootNode());a.sb=g.hh("iv-drawer-close-button",a.D);a.isInitialized=!0},Xfb=function(a){a.oa.push(g.Fv("iv-teaser-shown",a.f5,a));
a.oa.push(g.Fv("iv-teaser-hidden",a.paa,a));a.oa.push(g.Fv("iv-teaser-clicked",a.e5,a));a.Db=!0},Yfb=function(a,b){var c;
return b.onClickCommand&&((c=g.R(b.onClickCommand,g.Kcb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},Zfb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.CQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.R(h[0],g.u4a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},m3=function(a,b){if(!Yfb(a,b)||Zfb(a,b)){var c=$fb(a,b);
if(c){var d={Df:b,cP:c.element,T_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||Xfb(a),Ufb(a,b.id),c=a.findLastIndex(d),g.cc(a.cards,c,0,d));else{a.isInitialized||Wfb(a);Ufb(a,b.id);var e=a.findLastIndex(d);g.cc(a.cards,e,0,d);c.Ha(a.B,e);a.xJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,p3(a),agb(a,d),k3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&bgb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){bgb(a,d)}),p3(a))}}},$fb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",N:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Lfb(b);c={I:"div",Ka:["iv-card"],W:[{I:"a",N:"iv-click-target",Y:{href:b.url?c3(b.url)||"":""},W:[f3(b.imageUrl,c),{I:"div",N:"iv-card-content",W:[e3("h2",void 0,b.title),d]}]}]};c=new g.T(c);g3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],W:[{I:"a",Ka:["iv-click-target"],Y:{href:c3(b.url)||"","data-ytid":b.channelId},W:[f3(b.profileImageUrl),
{I:"div",N:"iv-card-content",W:[Jfb(b),{I:"h2",N:"iv-card-primary-link",xa:b.title},Kfb(b)]}]}]};c=new g.T(c);g3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],W:[{I:"a",N:"iv-click-target",Y:{href:c3(b.url)||""},W:[f3(b.rI,{I:"div",N:"iv-card-image-overlay",W:[{I:"span",N:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",N:"iv-card-content",W:[Jfb(b),e3("h2","iv-card-primary-link",b.title),Kfb(b)]}]}]};
c=new g.T(c);g3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Lfb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",N:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",N:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",W:e});e=b.url?c3(b.url)||"":"";c={I:"div",Ka:c,Y:{tabindex:"0"},W:[{I:"a",Ka:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",N:"iv-card-content",W:[b.sponsored?{I:"div",N:"iv-card-sponsored",W:["Sponsored",{I:"div",N:"iv-ad-info-container",W:[{I:"div",N:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",N:"iv-ad-info-icon-container",W:[{I:"div",N:"iv-ad-info-icon"},{I:"div",N:"iv-ad-info-callout"}]}]}]}:"",{I:"a",N:"iv-click-target",Y:{href:e},W:[e3("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.nh("span");g.uh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ed(d,"adInfo");g3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",N:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],W:[{I:"a",N:"iv-click-target",Y:{href:((c=b.url)==null?void 0:c3(c))||""},W:[f3(b.rI,d),{I:"div",N:"iv-card-content",W:[Jfb(b),e3("h2","iv-card-primary-link",b.title),Kfb(b),f]}]}]};c=new g.T(e);g3(a,g.fh("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},cgb=function(a){if(a.j)return a.j.Df.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Nl(a.cards,function(c){return c.Df.type==="productListing"})}return g.Nl(a.cards,function(c){return c.Df.type==="productListing"})},p3=function(a){g.Dp(a.J.getRootNode(),"ytp-cards-shopping-active",cgb(a))},bgb=function(a,b){if(!g.yp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Vw(),d=a.j?a.j.Df.If:a.If;
c&&d&&g.zx(c,[d]);a.j=b;p3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Df.teaserDurationMs&&a.J.DC(!0,{teaserText:b.Df.teaserText,durationMs:b.Df.teaserDurationMs,onClickCommand:b.Df.onClickCommand});a.gb.isActive()||((!a.C||!a.Ca.isActive()&&a.Ja)&&agb(a,b),a.gb.start(910+b.Df.teaserDurationMs))}},agb=function(a,b){a.X.Cb?(b=new S2([0,
a.B.scrollTop],[0,b.cP.offsetTop],600,ifb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Kx(a.X,!0),a.B.scrollTop=b.cP.offsetTop,g.Kx(a.X,!1))},q3=function(a){return a.j&&a.j.Df?a.j.Df:a.cards[0]&&a.cards[0].Df?a.cards[0].Df:null},Tfb=function(a,b){return g.Tb(a.cards,function(c){return c.Df.id===b})},r3=function(a,b,c){h3.call(this,a,b);
this.annotation=c;this.isActive=!1},dgb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},s3=function(a,b,c){r3.call(this,a,b,c);
this.B=null;this.T=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},egb=function(a,b){var c=c===void 0?0:c;
var d=$eb(b).width;g.Im(b,d);c=new gfb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,hfb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Om(b,!0)});
c.play()},hgb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.HY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Om(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Bm(l,"right",b.image_width+"px");g.ph(a.Ib(),l);a.C=new g.rp(function(){fgb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){ggb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},ggb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Nm(b);a.j||(b.style.width=g.Hm(f.width,!0),c.style.width=g.Hm(f.width,!0));g.Bm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Bm(d,"right","1px");a.D=!0;g.Om(b,!0);a.G=new g.rp(function(){g.zp(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},fgb=function(a,b,c){g.Bp(a.Ib(),"iv-branding-active");
a.K=new g.rp(function(){g.Om(b,!1);a.j||(c.style.width=g.Hm(0,!0))},250);
a.K.start();a.D=!1},igb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Z=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},jgb=function(a,b,c){r3.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.X=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.T=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.rp(function(){d.j.setAttribute("aria-hidden","true");g.Om(d.C,!1);g.Om(d.B,!0)},700,this);
g.P(this,this.G)},mgb=function(a,b,c){c.stopPropagation();
kgb(a);lgb(a,b);a.j.focus()},ngb=function(a){a.isCollapsed||a.V||a.D||(g.zp(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},kgb=function(a){a.G.stop();
a.isCollapsed&&(g.Cp(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Om(a.B,!1),g.Om(a.C,!0))},lgb=function(a,b){a.D||(a.D=g.Ki(function(){ogb(this);
ngb(this)},b,a))},ogb=function(a){a.D&&(g.Na.clearTimeout(a.D),a.D=null)},pgb=function(a){this.J=a},Vfb=function(a,b,c){b&&(c?t3(a,b.map(function(d){return g.Vo(d,c)})):t3(a,b))},t3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.mv(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},qgb=function(a){g.cY.call(this,a);
var b=this;this.oa=this.V=!1;this.loadNumber=0;this.K={};this.logger=new pgb(this.player);this.D=new g.aG(this);this.G=this.T=null;this.events=new g.aG(this);this.nh=this.X=this.j=null;this.qa=[];g.P(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.S(this.player,"resize",function(d){b.publish("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.g5,this);this.subscribe("resize",this.hM,this);this.player.U().Ja.subscribe("vast_info_card_add",this.l1,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",N:"video-custom-annotations"});this.B=new g.T({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.nS(this.player,this.B.element,4);this.B.hide();this.C=new g.T({I:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",N:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Lv()&&this.load();var c=this.createElement({I:"style"});(g.eh("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.sh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},rgb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Om(a,!1);return a},sgb=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.Kx(a.B,b);g.Kx(a.C,b)},tgb=function(a,b,c){a.V=!0;
a.G=g.Rr(b,c)},ugb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ta(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(ugb(a,e))}return c},ygb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Ja.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Gr(h)&&h.responseXML?h.responseXML:null)&&vgb(a,h)}};
g.ut()&&(d.onFinish=wgb(a,d.onFinish));d.postParams={ic_only:"1"};xgb(d,c);a.V=!0;g.Rr(b.Xa,d)}}},xgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.CJ&&(a.postParams.ic_coll=b.CJ);b.dP&&(a.postParams.ic_xml=b.dP);b.wN&&(a.postParams.ic_track=b.wN)},zgb=function(a){var b=new g.T({I:"div"});
g.Om(b.element,!1);var c=new Qfb(a.player,b.element,u3(a));g.P(c,b);b.Ha(a.B.element);c.aI();return c},Bgb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,Agb(a,b),b.headerText&&a.nh&&(c=g.Ox(b.headerText),a.nh.setAttribute("title",c))},u3=function(a){if(!a.X){var b=new jfb(a);
g.P(a,b);var c=new g.Lk(a);g.P(a,c);a.X=new igb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Qj)}return a.X},vgb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Vw();if(e){var f=g.Uw();f&&g.qr(g.ox)(void 0,e,f,[g.Sw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=ugb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=b3(f.type,Cgb),p=b3(f.style,Dgb),q=zfb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Ffb;if(t==null)var u=null;else if(g.Sa(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var E=f(t);u=E?[E]:[]}e=m&&n?new Gfb(m,n,p,u,r):null}else e=null}catch(ba){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=rgb(f),L=null;switch(l.type){case "branding":if(f.player.U().Fd)break;f.B.element.appendChild(H);L=new s3(H,u3(f),l);break;case "promotion":g.nS(f.player,H,4),L=new jgb(H,u3(f),l)}L&&L.aI();if(f=L)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=zgb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={SZ:f.impression,click:f.click,close:f.close,m3:f.teaser_impression,rN:f.teaser_click},l=e.tracking_params||{},L=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,yj:f,Zp:l.card?g.Sw(l.card):null,jk:l.teaser?g.Sw(l.teaser):null,If:l.icon?g.Sw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,yj:f,
Zp:l.card?g.Sw(l.card):null,jk:l.teaser?g.Sw(l.teaser):null,If:l.icon?g.Sw(l.icon):null,rI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "productListing":e.signin_url&&(L=d3({target:"current",value:e.signin_url}));N=[];for(var S=e.offers||[],W=0;W<S.length;W++)N.push(new Mfb(g.lg(S[W].merchant),
g.lg(S[W].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,yj:f,Zp:l.card?g.Sw(l.card):null,jk:l.teaser?g.Sw(l.teaser):null,If:l.icon?g.Sw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Gqa:L,Fqa:e.signin_title?e.signin_title:void 0,Eqa:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};m3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,yj:f,Zp:l.card?g.Sw(l.card):
null,jk:l.teaser?g.Sw(l.teaser):null,If:l.icon?g.Sw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,yj:f,Zp:l.card?g.Sw(l.card):null,jk:l.teaser?g.Sw(l.teaser):null,If:l.icon?g.Sw(l.icon):null,rI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},m3(H,c)}}else Rfb(a.j,e);c=!0}}c&&
(N2(a.player),a.hM())},Agb=function(a,b){var c=!1;
a.j||(a.j=zgb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Sfb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.DR(f)||(c=a.j,d=b.headerText?g.Ox(b.headerText):"",g.uh(c.Jb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.Sw(b.trackingParams):null,c.T=b.closeButton.infoCardIconRenderer.trackingParams?g.Sw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.If=b.icon.infoCardIconRenderer.trackingParams?g.Sw(b.icon.infoCardIconRenderer.trackingParams):null,a.hM());N2(a.player)}},Egb=function(a,b,c,d,e){if(!a.player.U().Fd){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.wR)&&g.R(b.navigationEndpoint,g.wR).browseId&&f.push(new Cfb("openUrl","click",new Afb("/channel/"+g.R(b.navigationEndpoint,g.wR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.xR)){d.channel_id=g.R(b.subscribeButton,g.xR).channelId;var l;b=g.R(b.subscribeButton,g.xR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Ox(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Ox(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Ox(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Ox(b.subscriberCountWithSubscribeText)));var m,n=((m=g.R((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.G1))==null?void 0:m.url)||"";l={subscribeText:g.Ox(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Ox(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Gfb(c,"branding","branding",f,d);l=rgb(a);a.B.element.appendChild(l);f=new s3(l,u3(a),f);f.aI();g.P(f,f);a.K[c]=f}},wgb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.Ia()||a.qa.push(g.kp.aj(function(){b.apply(null,g.x(c))}))}},Fgb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.gS.prototype.DC=g.da(35,function(a,b){var c=g.pY(this.Ab());c&&c.DC(a,b)});
var P2={},Q2=null;g.bb(S2,g.Ep);g.k=S2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;R2(this);this.startTime=a=g.Za();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.XL();this.Ao("play");this.isPaused()&&this.Ao("resume");this.j=1;var b=g.Wa(this);b in P2||(P2[b]=this);cfb();dfb(this,a);return!0};
g.k.stop=function(a){R2(this);this.j=0;a&&(this.progress=1);efb(this,this.progress);this.onStop();this.Gs()};
g.k.pause=function(){this.isPlaying()&&(R2(this),this.j=-1,this.Ao("pause"))};
g.k.va=function(){this.j==0||this.stop(!1);this.Ao("destroy");S2.Uf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.ON=function(){this.Ao("animate")};
g.k.Ao=function(a){this.dispatchEvent(new ffb(a,this))};
g.bb(ffb,g.Zh);g.bb(T2,S2);T2.prototype.C=function(){};
T2.prototype.ON=function(){this.C();T2.Uf.ON.call(this)};
T2.prototype.Gs=function(){this.C();T2.Uf.Gs.call(this)};
T2.prototype.XL=function(){this.C();T2.Uf.XL.call(this)};
g.bb(gfb,T2);gfb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(jfb,g.O);g.k=jfb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=g.Os(a,b,c);this.j.push(a);return a};
g.k.BG=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=afb(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.Ps(a);g.Xb(this.j,a)};
g.k.removeAll=function(){g.Ps(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.O.prototype.va.call(this)};g.z(mfb,g.cY);g.k=mfb.prototype;g.k.load=function(){g.cY.prototype.load.call(this);if(!W2(this)){var a=g.AMa(this.player.getVideoData());a?(a=lfb(a,nfb(this)),X2(this,a,!1)):ofb(this)}};
g.k.unload=function(){X2(this,null);this.C&&(this.C.abort(),this.C=null);g.cY.prototype.unload.call(this)};
g.k.ji=function(a,b){return W2(this)?a==="loadCustomEndscreenRenderer"?(a=lfb(b,"new"),X2(this,a),!0):null:null};
g.k.getOptions=function(){return W2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.lc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Ggb.length;f++){var h=Math.abs(b.width-Ggb[f]);if(e===-1||d>=h)e=f,d=h}d=Hgb[e];this.B&&g.Bm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Mm(e.element,m,f);g.Im(e.element,n,p);g.Cp(e.element,Igb);m>256||f>256?g.zp(e.element,"ytp-ce-large-round"):m>96||f>96?g.zp(e.element,"ytp-ce-medium-round"):g.zp(e.element,"ytp-ce-small-round");g.Cp(e.element,Jgb);m=h.left+h.width/2;h=h.top+l/2;g.zp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Cp(e.element,Hgb);g.zp(e.element,d);(e=g.gh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Bm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")a3(this,this.endscreen.impressionUrls),(a=g.Vw())&&this.endscreen.visualElement&&g.xx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.zp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.zp(b,"ytp-ce-shown");a3(this,c.impressionUrls);(b=g.Vw())&&g.xx(b,c.visualElement);this.player.U().T&&this.player.fb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Bp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Bp(b,"ytp-ce-shown");this.player.U().T&&this.player.fb("endscreenelementhidden",a)}};
g.k.wda=function(a){var b=this;a.target===window&&(new g.rp(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Cp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Ggb=[346,426,470,506,570,640,853,1280,1920],Hgb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Jgb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Igb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Bfb={Wha:"current",Bka:"new"};var Dfb={CLOSE:"close",Gka:"openUrl",SUBSCRIBE:"subscribe"},Efb={Fha:"click",CLOSE:"close",Yia:"hidden",xla:"rollOut",yla:"rollOver",Ila:"shown"};Gfb.prototype.oe=function(){var a=Hfb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Dgb={Qga:"anchored",G4:"branding",CHANNEL:"channel",Vha:"cta",bja:"highlightText",Oja:"label",PLAYLIST:"playlist",POPUP:"popup",Qla:"speech",SUBSCRIBE:"subscribe",bma:"title",VIDEO:"video",Lma:"website"},Cgb={G4:"branding",tha:"card",jia:"drawer",aja:"highlight",fka:"marker",ela:"promotion",TEXT:"text",nna:"widget"};g.z(h3,g.O);g.k=h3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.yE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Xa.set(a,e);this.context.J.df([a],1)};
g.k.aI=function(){this.context.B.subscribe("resize",this.xJ,this)};
g.k.Ib=function(){return this.element};
g.k.PN=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.sh(this.Ib())};
g.k.xJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=c3(a);if(f){var h=Ofb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Lf||!1,n=g.wr(f||"");m&&n&&(n.v||n.list)?e.context.J.Ip(n.v,b,n.list,!1):g.oz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);t3(this.context.logger,c,l,d);Nfb(f)||(c=g.Vw(),d=b.itct,c&&d&&g.Ax(c,g.Sw(d)))}};
g.k.va=function(){this.Ta.clear();this.Xa.clear();g.O.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.P(this,a);return a.element};g.z(Qfb,h3);g.k=Qfb.prototype;g.k.Bu=function(){this.qa&&m3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Nm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.xJ=function(){var a=this.isAvailable();g.Om(this.Ib(),a);g.Dp(this.context.J.getRootNode(),g.M_.IV_DRAWER_ENABLED,a);N2(this.J)};
g.k.destroy=function(){this.J.DC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.Gv(this.oa);g.Vs(this.Oa);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();h3.prototype.destroy.call(this)};
g.k.jJ=function(){var a=this;this.context.j.listen(g.hh("iv-drawer-close-button",this.D),"click",this.h8,this);this.context.j.listen(this.B,"touchend",function(){a.Ca.start()});
this.context.j.listen(this.B,"scroll",this.F8,this);this.context.B.subscribe("onHideControls",function(){a.Ja=!0});
this.context.B.subscribe("onShowControls",function(){a.Ja=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Ja=g.yp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.Fv("iv-button-shown",this.oaa,this));this.oa.push(g.Fv("iv-button-hidden",this.naa,this));Xfb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Ub(this.cards,function(c){return a.Df.startMs>c.Df.startMs||a.Df.startMs===c.Df.startMs&&a.Df.timestamp>=c.Df.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.h8=function(){if(this.C){t3(this.context.logger,q3(this).yj.close);var a=g.Vw();a&&this.T&&g.Ax(a,this.T);l3(this)}};
g.k.F8=function(){g.Dp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.oaa=function(){var a=g.Vw(),b=q3(this);b=b?b.If:this.If;a&&b&&g.yx(a,[b])};
g.k.naa=function(){var a=g.Vw(),b=q3(this);b=b?b.If:this.If;a&&b&&g.zx(a,[b])};
g.k.f5=function(){var a=q3(this);t3(this.context.logger,a.yj.m3);var b=g.Vw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.jk&&c.push(a.jk);a.If&&c.push(a.If);c.length>0&&g.yx(b,c)}else g.yx(b,[a.jk,a.If])};
g.k.paa=function(){var a=g.Vw(),b=q3(this);a&&b&&g.zx(a,[b.jk])};
g.k.e5=function(a){var b=q3(this),c=g.Vw();this.j?a?(a=this.context.logger,t3(a,b.yj.rN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.jk&&g.Ax(c,b.jk)):(a=this.context.logger,t3(a,b.yj.rN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.If&&g.Ax(c,b.If)):(a=this.context.logger,t3(a,b.yj.rN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.If&&g.Ax(c,this.If))};g.z(r3,h3);r3.prototype.aI=function(){h3.prototype.aI.call(this);dgb(this)};
r3.prototype.show=function(){h3.prototype.show.call(this);var a=g.Vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yx(a,[g.Sw(b.itct)])};
r3.prototype.hide=function(){h3.prototype.hide.call(this);var a=g.Vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zx(a,[g.Sw(b.itct)])};g.z(s3,r3);
s3.prototype.fz=function(){g.zp(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Om(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.oe();c&&i3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||hgb(this,
a)};
s3.prototype.show=function(){if(!this.isActive&&(r3.prototype.show.call(this),this.T||(this.fz(),this.T=!0),g.Om(this.Ib(),!0),this.isActive=!0,this.B)){try{egb(this,this.B)}catch(a){}g.zp(this.context.J.getRootNode(),"ytp-branding-shown")}};
s3.prototype.hide=function(){this.isActive&&(r3.prototype.hide.call(this),g.Om(this.Ib(),!1),this.isActive=!1,g.Bp(this.context.J.getRootNode(),"ytp-branding-shown"))};
s3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);r3.prototype.destroy.call(this)};g.z(jgb,r3);g.k=jgb.prototype;
g.k.fz=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.oe(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",N:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",N:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&i3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",N:"iv-promo-txt"}),g.Uf(f,c3(e)),this.j=f):this.j=this.createElement({I:"div",N:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",W:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",W:[{I:"span",N:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],W:[{I:"span",N:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&i3(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.zp(this.j,"iv-click-target");e&&i3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",W:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",W:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.zp(this.j,"iv-click-target"),e&&i3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.T.appendChild(this.j);p&&this.T.appendChild(p);c=this.createElement({I:"div",N:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){mgb(a,5E3,q)});
c.appendChild(this.B);g.Om(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.i$,this);this.context.j.listen(this.Ib(),"mouseout",this.h$,this);this.context.j.listen(this.Ib(),"touchend",function(q){mgb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.d$:this.c$,this);c.appendChild(this.C);g.Ap(this.Ib(),d);h&&(g.ph(this.Ib(),h),n&&h.appendChild(n));g.ph(this.Ib(),this.T);g.ph(this.Ib(),c)};
g.k.show=function(){this.isActive||(r3.prototype.show.call(this),this.X||(this.fz(),this.X=!0),g.Om(this.Ib(),!0),g.Ki(function(){g.Bp(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,ogb(this),kgb(this),lgb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.zp(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.PN=function(a,b,c,d,e,f){return this.isCollapsed?!1:r3.prototype.PN.call(this,a,b,c,d,e,f)};
g.k.i$=function(a){this.V=!0;mgb(this,500,a)};
g.k.h$=function(){this.V=!1;ngb(this)};
g.k.c$=function(a){a.stopPropagation();this.hide()};
g.k.d$=function(a){a.stopPropagation();ogb(this);this.isCollapsed=!0;g.zp(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();r3.prototype.destroy.call(this)};g.z(qgb,g.cY);g.k=qgb.prototype;g.k.ji=function(a,b){if(!Fgb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.j1(b))&&vgb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Ufb(this.j,b),N2(this.player)),!0}return null};
g.k.getOptions=function(){return Fgb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Lv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.NR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.q4||a.Ja.get(b.videoId)||g.ER(b)||g.BMa(b)?!0:!1};
g.k.hM=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Mm(this.C.element,a.width,a.height);g.Im(this.C.element,a.left,a.top)}if(this.j){var b=this.player.fn();a=this.j;b=b.width;g.Dp(a.D,"iv-drawer-small",b<=426);g.Dp(a.D,"iv-drawer-big",b>=1280)}};
g.k.g5=function(a){sgb(this,a.state);g.V(a.state,2)&&(this.Kl()&&this.Wp()&&this.player.getPresentingPlayerType()!==2&&this.EC(!1),this.DC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Gr(h)&&h.responseXML?h.responseXML:null)&&(vgb(b,h),g.zp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.cY.prototype.load.call(this);sgb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.ut()&&(a=wgb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ja.get(d);f&&xgb(e,f);f=f&&(f.dP||f.CJ);if(!c.Bw||f)c.Xa?tgb(this,c.Xa,e):(this.T=function(){if(!b.V)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.DR(h))&&!b.oa&&Bgb(b,h)},this.player.addEventListener("videodatachange",this.T));
g.nS(this.player,this.C.element,4);this.hM();(f=g.ER(c))&&Agb(this,f);(f=g.BMa(c))&&f.featuredChannel&&Egb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.nh=g.hh("ytp-cards-button",this.player.getRootNode());g.DR(c)&&Bgb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&tgb(this,b.Xa,a)};
g.k.unload=function(){this.player.Ze("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.X=null;this.j&&(this.j.destroy(),this.j=null,N2(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.cY.prototype.unload.call(this);this.C.detach();this.T&&(this.player.removeEventListener("videodatachange",this.T),this.T=null)};
g.k.l1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ygb(this):this.load())};
g.k.Kl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Wp=function(){return!!this.j&&this.j.C};
g.k.EC=function(a,b,c){b=b===void 0?!1:b;this.Kl();this.j&&(a?c?k3(this.j,c,b):k3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):l3(this.j))};
g.k.DC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Ja.unsubscribe("vast_info_card_add",this.l1,this);g.Bp(this.player.getRootNode(),g.M_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.kp,c=0,d=a.length;c<d;c++)b.zk(a[c]);this.qa.length=0;g.cY.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.P(this,a);return a.element};g.bY("annotations_module",qgb);g.bY("creatorendscreen",mfb);})(_yt_player);
